title: Threat Base
email: cmosher01@gmail.com
description: Copyright © 1996–2019, Christopher Alan Mosher, Shelton, Connecticut, USA.
repository: https://github.com/cmosher01/threatbase
github_username: cmosher01
baseurl: /threatbase
audio_baseurl: https://mosher.mine.nu/audio
image_baseurl: https://mosher.mine.nu/images
markdown: kramdown
theme: minima
collections:
  bands:
    output: true
  shows:
    output: true
  sessions:
    output: true
  discography:
    output: true
  extras:
    output: true
defaults:
  - scope:
      type: bands
    values:
      layout: band
  - scope:
      type: shows
    values:
      layout: show
