title: Threat Base
email: cmosher01@gmail.com
description: This is the new and improved database of Minor Threat.
repository: https://github.com/cmosher01/threatbase
github_username: cmosher01
baseurl: /threatbase
markdown: kramdown
theme: minima
collections:
  bands:
    output: true
  shows:
    output: true
  sessions:
    output: true
  discography:
    output: true
  extras:
    output: true
defaults:
  - scope:
      type: bands
    values:
      layout: band
  - scope:
      type: shows
    values:
      layout: show
